"""Restore missing user_info migration

Revision ID: 20251025_user_info
Revises: 97a3534d046a
Create Date: 2025-11-11 20:20:30.670113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '20251025_user_info'
down_revision: Union[str, None] = '97a3534d046a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create the user_notes table
    op.create_table('user_notes',
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('note', sa.Text(), nullable=True),
        sa.Column('subscription_duration', sa.Integer(), nullable=True),
        sa.Column('subscription_data_limit_gb', sa.Integer(), nullable=True),
        sa.Column('subscription_price', sa.Integer(), nullable=True),
        sa.Column('is_test_account', sa.Boolean(), nullable=False, server_default=sa.text('0')),
        sa.PrimaryKeyConstraint('username')
    )
    
    # Add new columns to the users table
    op.add_column('users', sa.Column('wallet_balance', sa.DECIMAL(precision=15, scale=2), nullable=False, server_default=sa.text("'0.00'")))
    op.add_column('users', sa.Column('test_accounts_received', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('users', sa.Column('admin_note', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('last_activity', sa.TIMESTAMP(), nullable=True))
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop new columns from the users table
    op.drop_column('users', 'last_activity')
    op.drop_column('users', 'admin_note')
    op.drop_column('users', 'test_accounts_received')
    op.drop_column('users', 'wallet_balance')
    
    # Drop the user_notes table
    op.drop_table('user_notes')
    
    # ### end Alembic commands ###