"""Add panel_id to template_config v2

Revision ID: 2ca1733599aa
Revises: 53d496294500
Create Date: 2025-11-08 07:22:53.473951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ca1733599aa'
down_revision: Union[str, None] = '53d496294500'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('template_config', sa.Column('panel_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'template_config', ['panel_id'])
    op.create_foreign_key(None, 'template_config', 'panel_credentials', ['panel_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'template_config', type_='foreignkey')
    op.drop_constraint(None, 'template_config', type_='unique')
    op.drop_column('template_config', 'panel_id')
    # ### end Alembic commands ###
