"""Add is_test_panel column to panel_credentials table

Revision ID: 53d496294500
Revises: 03e1608f0de8
Create Date: 2025-10-31 16:10:44.135214

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53d496294500'
down_revision: Union[str, None] = '03e1608f0de8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('panel_credentials', sa.Column('is_test_panel', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('panel_credentials', 'is_test_panel')
    # ### end Alembic commands ###
