"""initial schema

Revision ID: 9baa2159b600
Revises: 
Create Date: 2025-11-12 05:39:55.425595

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9baa2159b600'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_daily_notes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bot_managed_users',
    sa.Column('marzban_username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('marzban_username')
    )
    op.create_table('bot_settings',
    sa.Column('setting_key', sa.String(length=255), nullable=False),
    sa.Column('setting_value', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('setting_key')
    )
    op.create_table('financial_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_number', sa.String(length=255), nullable=True),
    sa.Column('card_holder', sa.String(length=255), nullable=True),
    sa.Column('price_per_gb', sa.Integer(), nullable=True),
    sa.Column('price_per_day', sa.Integer(), nullable=True),
    sa.Column('base_daily_price', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('guides',
    sa.Column('guide_key', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('photo_file_id', sa.Text(), nullable=True),
    sa.Column('buttons', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('guide_key')
    )
    op.create_table('non_renewal_users',
    sa.Column('marzban_username', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('marzban_username')
    )
    op.create_table('panel_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('panel_type', sa.Enum('MARZBAN', 'XUI', 'MARZNESHIN', name='paneltype'), nullable=False),
    sa.Column('api_url', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('is_test_panel', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('unlimited_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('plan_name', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('max_ips', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_notes',
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('subscription_duration', sa.Integer(), nullable=True),
    sa.Column('subscription_data_limit_gb', sa.Integer(), nullable=True),
    sa.Column('subscription_price', sa.Integer(), nullable=True),
    sa.Column('is_test_account', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('username')
    )
    op.create_table('users',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('join_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('wallet_balance', sa.DECIMAL(precision=15, scale=2), nullable=False),
    sa.Column('test_accounts_received', sa.Integer(), nullable=False),
    sa.Column('admin_note', sa.Text(), nullable=True),
    sa.Column('last_activity', sa.TIMESTAMP(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('volumetric_pricing_tiers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tier_name', sa.String(length=100), nullable=False),
    sa.Column('volume_limit_gb', sa.Integer(), nullable=False),
    sa.Column('price_per_gb', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('volume_limit_gb')
    )
    op.create_table('broadcasts',
    sa.Column('broadcast_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('admin_id', sa.BigInteger(), nullable=False),
    sa.Column('message_content', sa.JSON(), nullable=False),
    sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('broadcast_id')
    )
    op.create_table('marzban_telegram_links',
    sa.Column('marzban_username', sa.String(length=255), nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=False),
    sa.Column('auto_renew', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['panel_id'], ['panel_credentials.id'], ),
    sa.ForeignKeyConstraint(['telegram_user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('marzban_username')
    )
    op.create_index(op.f('ix_marzban_telegram_links_telegram_user_id'), 'marzban_telegram_links', ['telegram_user_id'], unique=False)
    op.create_table('pending_invoices',
    sa.Column('invoice_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('plan_details', sa.JSON(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('from_wallet_amount', sa.Integer(), server_default='0', nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('invoice_id')
    )
    op.create_index(op.f('ix_pending_invoices_user_id'), 'pending_invoices', ['user_id'], unique=False)
    op.create_table('template_config',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('panel_id', sa.Integer(), nullable=False),
    sa.Column('template_username', sa.String(length=255), nullable=False),
    sa.Column('proxies', sa.JSON(), nullable=True),
    sa.Column('inbounds', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['panel_id'], ['panel_credentials.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('panel_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('template_config')
    op.drop_index(op.f('ix_pending_invoices_user_id'), table_name='pending_invoices')
    op.drop_table('pending_invoices')
    op.drop_index(op.f('ix_marzban_telegram_links_telegram_user_id'), table_name='marzban_telegram_links')
    op.drop_table('marzban_telegram_links')
    op.drop_table('broadcasts')
    op.drop_table('volumetric_pricing_tiers')
    op.drop_table('users')
    op.drop_table('user_notes')
    op.drop_table('unlimited_plans')
    op.drop_table('panel_credentials')
    op.drop_table('non_renewal_users')
    op.drop_table('guides')
    op.drop_table('financial_settings')
    op.drop_table('bot_settings')
    op.drop_table('bot_managed_users')
    op.drop_table('admin_daily_notes')
    # ### end Alembic commands ###
