"""add_admin_id_to_managed_users

Revision ID: c789f3e6af07
Revises: 1dd54c0b2fa2
Create Date: 2025-11-23 03:29:12.006156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c789f3e6af07'
down_revision: Union[str, None] = '1dd54c0b2fa2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_managed_users', sa.Column('created_by_admin_id', sa.BigInteger(), nullable=True))
    op.drop_index('idx_managed_username', table_name='bot_managed_users')
    op.create_foreign_key(None, 'marzban_telegram_links', 'users', ['telegram_user_id'], ['user_id'])
    op.create_foreign_key(None, 'marzban_telegram_links', 'panel_credentials', ['panel_id'], ['id'])
    op.drop_index('idx_panel_id', table_name='panel_credentials')
    op.alter_column('pending_invoices', 'from_wallet_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.alter_column('pending_invoices', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('pending_invoices', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('user_id_idx', table_name='pending_invoices')
    op.create_index(op.f('ix_pending_invoices_user_id'), 'pending_invoices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pending_invoices', 'users', ['user_id'], ['user_id'])
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'join_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'join_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'pending_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_pending_invoices_user_id'), table_name='pending_invoices')
    op.create_index('user_id_idx', 'pending_invoices', ['user_id'], unique=False)
    op.alter_column('pending_invoices', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('pending_invoices', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('pending_invoices', 'from_wallet_amount',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.create_index('idx_panel_id', 'panel_credentials', ['id'], unique=False)
    op.drop_constraint(None, 'marzban_telegram_links', type_='foreignkey')
    op.drop_constraint(None, 'marzban_telegram_links', type_='foreignkey')
    op.create_index('idx_managed_username', 'bot_managed_users', ['marzban_username'], unique=False)
    op.drop_column('bot_managed_users', 'created_by_admin_id')
    # ### end Alembic commands ###
