"""Initial migration with all tables

Revision ID: ff13492121a5
Revises: 20251025_user_info
Create Date: 2025-11-16 14:14:25.641076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ff13492121a5'
down_revision: Union[str, None] = '20251025_user_info'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # --- Manual Adjustment for Data Preservation ---
    # Rename the old table to the new table to keep the data.
    op.rename_table('marzban_credentials', 'panel_credentials')

    # Now, alter the renamed table to match the new schema.
    # Add new columns with temporary defaults if needed
    op.add_column('panel_credentials', sa.Column('name', sa.String(length=100), nullable=False, server_default='Default Panel'))
    op.add_column('panel_credentials', sa.Column('panel_type', sa.Enum('MARZBAN', 'XUI', 'MARZNESHIN', name='paneltype'), nullable=False, server_default='MARZBAN'))
    op.add_column('panel_credentials', sa.Column('is_test_panel', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # Rename the old 'base_url' column to 'api_url'
    op.alter_column('panel_credentials', 'base_url', new_column_name='api_url', existing_type=sa.String(length=255), existing_nullable=False)

    # Make the id column auto-incrementing
    op.alter_column('panel_credentials', 'id',
               existing_type=mysql.INTEGER(display_width=11),
               autoincrement=True,
               nullable=False)

    # Add the unique constraint on the 'name' column after it's populated
    op.create_unique_constraint('uq_panel_credentials_name', 'panel_credentials', ['name'])
    # --- End of Manual Adjustment ---

    op.alter_column('admin_daily_notes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.add_column('broadcasts', sa.Column('broadcast_id', sa.Integer(), autoincrement=True, nullable=False))
    op.add_column('broadcasts', sa.Column('admin_id', sa.BigInteger(), nullable=False))
    op.add_column('broadcasts', sa.Column('message_content', sa.JSON(), nullable=False))
    op.add_column('broadcasts', sa.Column('sent_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False))
    op.add_column('broadcasts', sa.Column('success_count', sa.Integer(), nullable=False))
    op.add_column('broadcasts', sa.Column('failure_count', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'broadcasts', 'users', ['admin_id'], ['user_id'])
    op.drop_column('broadcasts', 'photo_id')
    op.drop_column('broadcasts', 'target_user_ids')
    op.drop_column('broadcasts', 'created_at')
    op.drop_column('broadcasts', 'text')
    op.drop_column('broadcasts', 'job_id')
    op.drop_column('broadcasts', 'buttons')
    op.add_column('marzban_telegram_links', sa.Column('panel_id', sa.Integer(), nullable=False, server_default='1'))
    op.drop_index('telegram_user_id_idx', table_name='marzban_telegram_links')
    op.create_index(op.f('ix_marzban_telegram_links_telegram_user_id'), 'marzban_telegram_links', ['telegram_user_id'], unique=False)

    # --- Manual Data Integrity Fix ---
    # Delete orphaned rows from marzban_telegram_links before creating the foreign key.
    op.execute(
        """
        DELETE mtl FROM marzban_telegram_links AS mtl
        LEFT JOIN users ON mtl.telegram_user_id = users.user_id
        WHERE users.user_id IS NULL
        """
    )
    # --- End of Manual Fix ---

    op.create_foreign_key(None, 'marzban_telegram_links', 'users', ['telegram_user_id'], ['user_id'])
    op.create_foreign_key(None, 'marzban_telegram_links', 'panel_credentials', ['panel_id'], ['id'])
    op.alter_column('pending_invoices', 'from_wallet_amount',
               existing_type=mysql.DECIMAL(precision=15, scale=2),
               type_=sa.Integer(),
               existing_nullable=True,
               existing_server_default=sa.text('0.00'))
    op.alter_column('pending_invoices', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('pending_invoices', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    op.drop_index('user_id_idx', table_name='pending_invoices')
    op.create_index(op.f('ix_pending_invoices_user_id'), 'pending_invoices', ['user_id'], unique=False)
    op.create_foreign_key(None, 'pending_invoices', 'users', ['user_id'], ['user_id'])
    op.add_column('template_config', sa.Column('panel_id', sa.Integer(), nullable=False, server_default='1'))
    op.create_unique_constraint(None, 'template_config', ['panel_id'])
    op.create_foreign_key(None, 'template_config', 'panel_credentials', ['panel_id'], ['id'])
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'join_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('current_timestamp()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'join_date',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('users', 'is_admin',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'template_config', type_='foreignkey')
    op.drop_constraint(None, 'template_config', type_='unique')
    op.drop_column('template_config', 'panel_id')
    op.drop_constraint(None, 'pending_invoices', type_='foreignkey')
    op.drop_index(op.f('ix_pending_invoices_user_id'), table_name='pending_invoices')
    op.create_index('user_id_idx', 'pending_invoices', ['user_id'], unique=False)
    op.alter_column('pending_invoices', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.alter_column('pending_invoices', 'status',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True,
               existing_server_default=sa.text("'pending'"))
    op.alter_column('pending_invoices', 'from_wallet_amount',
               existing_type=sa.Integer(),
               type_=mysql.DECIMAL(precision=15, scale=2),
               existing_nullable=False,
               existing_server_default=sa.text('0.00'))
    op.drop_constraint(None, 'marzban_telegram_links', type_='foreignkey')
    op.drop_constraint(None, 'marzban_telegram_links', type_='foreignkey')
    op.drop_index(op.f('ix_marzban_telegram_links_telegram_user_id'), table_name='marzban_telegram_links')
    op.create_index('telegram_user_id_idx', 'marzban_telegram_links', ['telegram_user_id'], unique=False)
    op.drop_column('marzban_telegram_links', 'panel_id')
    op.add_column('broadcasts', sa.Column('buttons', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('broadcasts', sa.Column('job_id', mysql.VARCHAR(length=36), nullable=False))
    op.add_column('broadcasts', sa.Column('text', mysql.TEXT(), nullable=True))
    op.add_column('broadcasts', sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('current_timestamp()'), nullable=True))
    op.add_column('broadcasts', sa.Column('target_user_ids', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
    op.add_column('broadcasts', sa.Column('photo_id', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'broadcasts', type_='foreignkey')
    op.drop_column('broadcasts', 'failure_count')
    op.drop_column('broadcasts', 'success_count')
    op.drop_column('broadcasts', 'sent_at')
    op.drop_column('broadcasts', 'message_content')
    op.drop_column('broadcasts', 'admin_id')
    op.drop_column('broadcasts', 'broadcast_id')
    op.alter_column('admin_daily_notes', 'created_at',
               existing_type=mysql.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('current_timestamp()'))
    op.create_table('marzban_credentials',
    sa.Column('id', mysql.INTEGER(display_width=11), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('base_url', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('panel_credentials')
    # ### end Alembic commands ###
